### PR TITLE
to send `NOTIFICATION` or not to send `NOTIFICATION`

### PR DESCRIPTION
**Pull request by benmaddison**
- more nits
- deal with `NOTIFICATION` paradoxes

### CODE REVIEW

**Comment by randomthingsandstuff** [comment]
i think you got the notification complaint addressed pretty well. somewhat not sure (based on implementations, lore, etc) if the discussion on notifications should be included directly in this draft, if for no other reason that it opens up several cans of worms re: e.g. Holdtimer expiry notification when socket is blocked and how that should be handled.

not sure if there should actually be a separate clarifying I-D to sort that out more fully.

**Comment by job** [comment]
Another I-D is not a feasible option :)

**Comment by randomthingsandstuff** [comment]
> Another I-D is not a feasible option :)

i mean, i'm not saying its mandatory to get this one out the door, but rather a bit more in-depth discussion on what to do when socket is blocked aside from this mechanism.

like example, what happens when we're supposed to send a notification in other circumstances and its blocked? do we wait for sendholdtimer to finish the rest of the transition back to idle?

**Comment by benmaddison** [comment]
Yeah @randomthingsandstuff, while re-reading 4271 and friends to try work out how to word this, I basically came to the conclusion that "send `NOTIFICATION` without blocking if you can be sure, then kill the socket" is actually the right language for terminal events in general, not just `SendHoldTimer_Expires`.

I chose not to open that can of worms on the mailing list the Monday after IETF week ;-)

I think the principle is even broader: don't make actions that transition between FSM states dependent on non-local state. The existing language in 4271 seems to discount the possibility that sending a message has such a dependency. That is the shortcoming that led to this draft coming into existence in the first place.

I would be supportive of a follow-up fixing the FSM blocking issue in the future, but I wouldn't want to see it tacked-on here.

**Comment by job** [comment]
Ben Cox and I attempted to resolve it this way: https://github.com/bgp/draft-ietf-idr-bgp-sendholdtimer/commit/7fa800136bbb4ed856cc2df4ab3f776d9d33bc86

ack?

**Comment by benmaddison** [comment]
@job and @benjojo, I've rebased over `master`, and in the process, most of the differences are now purely editorial (we're going to have to talk about semicolons sometime ;-))
I still prefer the `(optionally) sends ...` version in the FSM description, particularly for consistency with the use of `MAY` elsewhere. But I'm not going to die on that hill!

**Comment by randomthingsandstuff** [comment]
> Ben Cox and I attempted to resolve it this way: [7fa8001](https://github.com/bgp/draft-ietf-idr-bgp-sendholdtimer/commit/7fa800136bbb4ed856cc2df4ab3f776d9d33bc86)
> 
> ack?

lgtm

**Pull request merged**
